package com.mayur.pact.provider;

import au.com.dius.pact.provider.junit5.PactVerificationContext;
import au.com.dius.pact.provider.junit5.PactVerificationInvocationContextProvider;
import au.com.dius.pact.provider.junitsupport.Provider;
import au.com.dius.pact.provider.junitsupport.State;
import au.com.dius.pact.provider.junitsupport.loader.PactFolder;
import au.com.dius.pact.provider.spring.junit5.MockMvcTestTarget;
import com.mayur.pact.controller.UserController;
import com.mayur.pact.model.User;
import com.mayur.pact.service.UserService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.TestTemplate;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mockito;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.test.web.servlet.MockMvc;

import java.util.List;
import java.util.Optional;

/**
 * Provider verification test.
 *
 * Reads pact files from /pacts directory (generated by consumer tests)
 * and verifies that the provider (UserService) satisfies every contract.
 */
@ExtendWith({SpringExtension.class, PactVerificationInvocationContextProvider.class})
@WebMvcTest(UserController.class)
@Provider("UserService")
@PactFolder("../pacts")
class UserServiceProviderPactTest {

    @Autowired
    private MockMvc mockMvc;

    @MockBean
    private UserService userService;

    @BeforeEach
    void setupTestTarget(PactVerificationContext context) {
        context.setTarget(new MockMvcTestTarget(mockMvc));
    }

    @TestTemplate
    @ExtendWith(PactVerificationInvocationContextProvider.class)
    void verifyPact(PactVerificationContext context) {
        context.verifyInteraction();
    }

    // ── Provider states ──────────────────────────────────────────────────────

    @State("user with id 1 exists")
    void userWithId1Exists() {
        User user = User.builder()
                .id(1)
                .name("Mayur Sharma")
                .email("mayur@example.com")
                .role("QA_ENGINEER")
                .build();
        Mockito.when(userService.findById(1)).thenReturn(Optional.of(user));
    }

    @State("user with id 999 does not exist")
    void userWithId999DoesNotExist() {
        Mockito.when(userService.findById(999)).thenReturn(Optional.empty());
    }

    @State("at least one user exists")
    void atLeastOneUserExists() {
        List<User> users = List.of(
                User.builder().id(1).name("Mayur Sharma").email("mayur@example.com").role("QA_ENGINEER").build(),
                User.builder().id(2).name("Jane Doe").email("jane@example.com").role("TESTER").build()
        );
        Mockito.when(userService.findAll()).thenReturn(users);
    }

    @State("the user service is available")
    void userServiceIsAvailable() {
        User created = User.builder()
                .id(3)
                .name("Jane Doe")
                .email("jane@example.com")
                .role("TESTER")
                .build();
        Mockito.when(userService.create(Mockito.any(User.class))).thenReturn(created);
    }
}
